### ISSUE TITLE
create returnApplicants endpoint

### ISSUE THREAD

**Issue by khushi4243** [Code-4-Community/c4c-ops#7]
Goal: Recruiters should be able search through all other Members/Applicants, and find only the applicants. 

Task: Create an endpoint returnApplicants that meets the following criteria:

Request Schema: Take in a BOOLEAN returnApplicants as a parameter, default FALSE

Response Schema:
200 OK

```
{
  userId: STRING,
  status: STRING ('APPLICANT'),
  firstName: STRING,
  lastName: STRING,
  email: STRING,
}
```
400 BAD REQUEST
If any of the following are true:

- returnApplicants is TRUE and the calling user is not a RECRUITER or ADMIN

TODO THINK ABOUT OTHER BAD CASES WITH FILTER PARAMS
401 UNAUTHORIZED
If any of the following are true:

- the calling user is an APPLICANT
- the calling user is a MEMBER

**Comment by chromium-52** [comment]
Handled by #2 and #15
